### ISSUE TITLE
Natural Weapon Stacking Breaks Monk's Unarmed Strike

### ISSUE THREAD

**Issue by BellaRoka** [microsoftenator2022/MiscTweaksAndFixes#3]
As stated the Natural Weapon Stacking tweak breaks the Unarmed Strike feature from monk. At level 1 a medium sized monk with the tweak turned on has only a 1d3 Unarmed Strike, whereas turning it off reverts it back to how it should be- a 1d6 unarmed strike.

**Comment by BellaRoka** [comment]
After doing some more testing, disabling the Natural Weapon Stacking tweak isn't consistent in fixing the issue. Fully disabling the mod in Unity Mod Manager and restarting the game is sadly the only consistent fix right now.

**Comment by microsoftenator2022** [comment]
Being broken for monk is strange: it's supposed to ignore unarmed weapons entirely. Perhaps something in DLC3 broke it.

It also shouldn't have any effect at all if it's disabled in the settings, so perhaps a modmenu issue as well.

**Comment by microsoftenator2022** [comment]
Please test with this debug release:
https://github.com/microsoftenator2022/MiscTweaksAndFixes2/releases/download/2.0.0-dev/MiscTweaksAndFixes-1.9.9-debug.zip

If the issue persists, attach your player.log.
